Global:
  debug: false
  use_gpu: true
  epoch_num: 2000
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: /ihub/homedirs/am_cse/pramay/work/models/v3_devanagari_mobile_synth_100
  save_epoch_step: 3
  eval_batch_step: [500, 2000]
  cal_metric_during_train: true
  calc_epoch_interval: 50
  pretrained_model:
  checkpoints:
  save_inference_dir:
  use_visualdl: false
  character_dict_path: ppocr/utils/dict/devanagari_dict.txt
  max_text_length: &max_text_length 100
  infer_mode: false
  use_space_char: true
  distributed: true
  use_wandb: true


Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05


Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
    last_pool_kernel_size: [2, 2]
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: *max_text_length

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Train:
  dataset:
    name: SimpleDataSet
    data_dir: /ihub/homedirs/am_cse/pramay/work/Dataset/synth/large_set_100/
    ext_op_transform_idx: 1
    label_file_list:
    # - train_data/rec/rec_gt_train.txt
    - train_data/train_gt_synth.txt
    # ratio_list:
    # - 0.7
    # - 0.3
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape: [48, 320, 3]
        max_text_length: *max_text_length
    - RecAug:
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: true
    batch_size_per_card: 1024
    drop_last: true
    num_workers: 32
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: /ihub/homedirs/am_cse/pramay/work/Dataset/synth/large_set_100/
    label_file_list:
    - train_data/val_gt_synth.txt
    # ratio_list:
    # - 0.7
    # - 0.3
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
    - RecResizeImg:
        image_shape: [3, 48, 320]
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_sar
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 1024
    num_workers: 32